chipsec: Fix missing gcc issue
Sometimes, when building LUV, we see the following issue:
ERROR: chipsec-1.3.5-r0 do_make_scripts: Function failed:
do_make_scripts
| make[1]: Entering directory
../build/tmp/work-shared/qemux86-64/kernel-build-artifacts'
|
../build/tmp/work-shared/qemux86-64/kernel-source/scripts/gcc-version.sh:
line 26: x86_64-oe-linux-gcc: command not found
|
| make[1]: x86_64-oe-linux-gcc: Command not found
| make[1]: x86_64-oe-linux-gcc: Command not found
| make[1]: x86_64-oe-linux-gcc: Command not found
| make[1]: x86_64-oe-linux-gcc: Command not found
| make[1]: x86_64-oe-linux-gcc: Command not found

This is because bitbake tries to find gcc in an incorrect directory
specified in the DEPENDS variable i.e ${TARGET_PREFIX}gcc-initial.

Thus, remove this dependency.

Signed-off-by: Megha Dey <megha.dey@linux.intel.com>