sbsigntool: prevent unsafe cross-compilation
When cross-compiling, directories from the host machine are included in
EFI_CPPFLAGS. This triggers the following warning from the do_qa_configure
task:

  ERROR: This autoconf log indicates errors, it looked at host include
  and/or library paths while determining system capabilities.

In the autoconf config.log shows clearly the problem:

  cc1: warning: include location "/usr/include/efi" is unsafe for
  cross-compilation [-Wpoison-system-directories]
  cc1: warning: include location "/usr/include/efi/x86_64" is unsafe
  for cross-compilation [-Wpoison-system-directories]

Thus, a "=" is prepended to that the sysroot prefix is added,
as described in the gcc documentation.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>