linux-luv: Don't remove .cache.mk file
After bumping kernel to v4.18, build breaks (with below error) because
.cache.mk file is not present and kernel recipe tries to remove it.
Hence, do not attempt to remove the file.

ERROR: linux-luv-4.18+gitAUTOINC+94710cac0e-r5 do_configure: Function
failed: do_configure (log file is located at
<build>/tmp/work/qemux86_64-oe-linux/linux-luv/4.18+gitAUTOINC+94710cac0e-r5/temp/log.do_configure.2758)
ERROR: Logfile of failure stored in:
<build>/tmp/work/qemux86_64-oe-linux/linux-luv/4.18+gitAUTOINC+94710cac0e-r5/temp/log.do_configure.2758
Log data follows:
| DEBUG: Executing python function check_oldest_kernel
| DEBUG: Python function check_oldest_kernel finished
| DEBUG: Executing shell function do_configure
| rm: cannot remove
'<build>/tmp/work/qemux86_64-oe-linux/linux-luv/4.18+gitAUTOINC+94710cac0e-r5/linux-qemux86_64-standard-build/.cache.mk':
No such file or directory
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at
<build>/tmp/work/qemux86_64-oe-linux/linux-luv/4.18+gitAUTOINC+94710cac0e-r5/temp/log.do_configure.2758)
ERROR: Task
(/home/saipraneeth/luv-yocto/meta-luv/recipes-kernel/linux/linux-luv_4.17.bb:do_configure)
failed with exit code '1'

Cc: Naresh Bhat <naresh.bhat@linaro.org>
Cc: Megha Dey <megha.dey@linux.intel.com>
Cc: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>
Signed-off-by: Sai Praneeth Prakhya <sai.praneeth.prakhya@intel.com>