bits: grub: efidisk: respect block_io_protocol buffer alignment
This a backport of:

commit 51f375d688529b7c1819ba40188ee52b9333887c
Author: Leif Lindholm <leif.lindholm@linaro.org>
Date:   Sat Feb 27 13:44:59 2016 +0100

    efidisk: Respect block_io_protocol buffer alignment

from the grub development tree. Paraphrasing Leif's words, the
grub_efi_block_io_media contains the io_align field, which describes
the minimum alignment required for buffers used in data transfers
with device. Lief's approach is to create a temporary buffer for
the data transfers that meets the alignment requireements of the
device.

Recent updates to firmware implementations, including Tianocore,
enforce this alignment (i.e. EFI_INVALID_PARAMETER is returned on
unaligned buffers) described in the section 12.9 of the UEFI
specification.

This is especially critical when it is not trivial to ensure the
alignment of the data buffer (e.g, we need to write data starting
at an offset of the buffer). Such, scenario occurs when writing
testing results. If the alignment is not correct, the following
issue is observed:

   Traceback (most recent call last):
   File "", line 1, in
   File "/boot/python/init.py", line 246, in init
   redirect.write_logfile_cpio("/boot/bitsrd", "home/root/bits-log.txt")
   File "/boot/python/redirect.py", line 95, in write_logfile_cpio
   _bits.disk_write(f, sector, offset,
   logdata[bytes_written:bytes_written+leng
   th])
   IOError: [Errno 15] GRUB error 15

Further instrumentation of efidisk shows that the firmware issues
a EFI_INVALID_PARAMETER.

This is to fix https://github.com/01org/luv-yocto/issues/73.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>