luv-efi: use 'open' instead of 'file'
Now that bitbake is transitioning to python3, file is no longer supported.

Instead, use open. Otherwise, you will see this error:

ERROR: luv-live-image-1.0-r0 do_bootimg: Error executing a python
function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:build_efi_cfg(d)
     0003:
File: './meta-luv/classes/luv-efi.bbclass', lineno: 154, function: build_efi_cfg
     0150:    if not path:
     0151:        raise bb.build.FuncFailed('Unable to read GRUBCFG')
     0152:
     0153:    try:
 *** 0154:        cfgfile = file(path, 'w')
     0155:    except OSError:
     0156:        raise bb.build.funcFailed('Unable to open %s' % (cfgfile))
     0157:
     0158:    target = d.getVar('TARGET_ARCH', True)
Exception: NameError: name 'file' is not defined

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>