bits: grub:: util: of: complete handling of read return values
Return values of read are not checked for errors. This can lead to spurious
reads. Furthermore, it triggers the following compiler warning:

    build/grub/util/ieee1275/ofpath.c: In function 'find_obppath':
    build/grub/util/ieee1275/ofpath.c:146:11: error: ignoring return value of
        'read', declared with attribute warn_unused_result [-Werror=unused-result]
           read(fd, of_path, size);
               ^
    build/grub/util/ieee1275/ofpath.c: In function 'check_sas':
    build/grub/util/ieee1275/ofpath.c:357:8: error: ignoring return value of
        'read', declared with attribute warn_unused_result [-Werror=unused-result]
       read (fd, phy, sizeof (phy));
            ^
It makes sense to return NULL when reads fail, as the callers of this
function of find_obppath checks for NULL values when handing errors.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>