bits: python: compat: fix error handling lseek
By looking at the code, it is obvious that the intention is to print
an error message and return (off_t)-1 as seeking was unsuccessful.
Hence, this block of code needs to be wrapped in curly brackets.

Also, recent versions of gcc include checks for indentation. This will
trigger the following warning (or error if warnings are treated as
errors).

[...]/build/grub/grub-core/contrib/python/compat.c: In function 'lseek':
[...]/grub-core/contrib/python/compat.c:420:5: error: this 'if'
clause does not guard... [-Werror=misleading-indentation]
     if (fd >= 0 && fd < 3)
     ^~
[...]/build/grub/grub-core/contrib/python/compat.c:422:9: note:
...this statement, but the latter is misleadingly indented as if it is
guarded by the 'if'
         return (off_t)-1;
         ^~~~~~

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>