bits: python: zlib: fix a left shift of a negative value
When building the zlib library in python, the following error is
observed:

[...]/build/grub/grub-core/contrib-deps/python/Modules/zlib/inflate.c:
 In function 'inflateMark':
[...]/build/grub/grub-core/contrib-deps/python/Modules/zlib/inflate.c:1507:61:
 error: left shift of negative value [-Werror=shift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~

This has been fixed in

commit e54e1299404101a5a9d0cf5e45512b543967f958
Author: Mark Adler <madler@alumni.caltech.edu>
Date:   Sat Sep 5 17:45:55 2015 -0700

    Avoid shifts of negative values inflateMark().

from https://github.com/madler/zlib.git. Back-port such change here.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>