bits-python: _ctypes: do not use the WIN/64/EFI64 calling convention
The commit ID f6b5a91f417ac77d2fe9b0b3eb66293db132e2e in BITS implemented
support for the WIN64/EFI64. However, this was only implemented in the libffi
module that GRUB uses, not on the host Python implementation. Thus,
Python fails to build with the following error:

../build/python-host/Modules/_ctypes/callbacks.c:465:14: In function '_ctypes_alloc_callback':
error: 'FFI_EFI64' undeclared (first use in this function)
         cc = FFI_EFI64;
              ^
Hence, for now just do not use such calling convention in the host Python. This
effectively reverts commit 2e41220a584b0d4fcda5c95dc14cf638f9b9a331 in
the Python submodule of BITS.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>