nvdimm-test: make do_populate_lic depend on virtual/kernel's do_populate_lic
We use this recipe to build the kernel's nvdimm tests. Thus, this
code is covered unter the Linux license. However, bitbake might start
constructing the artifacts of this recipe before the Linux license has had
a chance to be exported and the following error is observed:

ERROR: nvdimm-test-1.0-r0 do_populate_lic: QA Issue: nvdimm-test:
LIC_FILES_CHKSUM points to an invalid file: [...]/build/tmp/work-shared
qemux86-64/kernel-source/COPYING [license-checksum]

Making this recipe's do_populate_lic on the kernel's do_populate_lic
ensures that we retrieve the license until it is available.

Cc: Megha Dey <megha.dey@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>