bits: Resolve 'storage size isn't known' error
When compiling bits, we see a new error after updating to the latest
poky:

..git/build/grub/grub-core/gettext/gettext.c:37:36:
error: storage size of 'main_context' isn't known
|  static struct grub_gettext_context main_context, secondary_context;
                                     ^~~~~~~~~~~~

This error occurs because the static structure is declared before it has been
defined. This patch ensures that the structure is first defined and only
then declared.

Signed-off-by: Megha Dey <megha.dey@linux.intel.com>