chipsec: make chipsec recipe depend on make_scripts
In order to out-of-tree build modules properly, it is necessary to invoke
make prepare && make scripts in the Linux source tree. Otherwise, the
module will not know all the appropriate kernel configurations. The task
make_scripts, inherited from module-base.bbclass, takes care of it.

CHIPSEC includes an out-of-tree module. Thus, make_scripts should run
before our do_compile task. Since in Yocto the Linux build artifacts are
put in a separate directory, controlled by the kernel's do_shared_workdir
task, such task must run before make_scripts.

Lastly, we hold a lock to the kernel-scripts task.

The issue of not running make_scripts before do_compile manifests itself
as:

ERROR: Kernel configuration is invalid.
      include/generated/autoconf.h or include/config/auto.conf are missing.
      Run 'make oldconfig && make prepare' on kernel src to fix it.

Cc: Megha Dey <megha.dey@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>