sbsigntool: update fetcher from git to gitsm
Till now, the sbsigntool recipe used git as its fetcher. Hence, the
associated submodules were being fetched in the do_configure task.
Ideally, all the sources should be fetched in the do_fetch task.

This patch switches to using the gitsm as the fetcher which makes the
code cleaner and is closely in line with other yocto recipes.

This is also a preparatory patch to the upcoming poky/pyro merge. Due to
the sanitization of the PATH variable, we will run into the following
error:
Submodule 'lib/ccan.git' (git://git.ozlabs.org/~ccan/ccan)
registered for path 'lib/ccan.git'
Cloning into 'lib/ccan.git'...
error: cannot run git-proxy-command.sh: No such file or directory
fatal: cannot start proxy git-proxy-command.sh
Clone of 'git://git.ozlabs.org/~ccan/ccan' into submodule path
'lib/ccan.git' failed

Reviewed-by: Ricardo Neri <ricardo.neri-calderon at linux.intel.com>
Signed-off-by: Megha Dey <megha.dey@linux.intel.com>