nvdimm-test: make this recipe a provider of libnvdimm
The selftests for the nvdimm subsystem provide drivers tweaked for testing.
This recipe already identify the artifacts as testing versions of the
actual drivers.

Several kernel drivers depend on libnvdimm (e.g. dax-pmem) and this
dependency is spelled out in the kernel source code. This dependency had
not been picked-up by bitbake until recently. Recent versions of the Yocto
Project will issue the following error due to dependencies not being met:

ERROR: core-image-efi-initramfs-1.0-r0 do_rootfs: Unable to install packages.
 Command '[...]/luv-yocto/build/tmp/sysroots/x86_64-linux/usr/bin/smart
 --log-level=warning...

Computing transaction...error: Can't install kernel-module-dax-pmem-4.7
+git0+ed08355a69_523d939ef9-r5@qemux86_64: no package provides
kernel-module-libnvdimm

ERROR: core-image-efi-initramfs-1.0-r0 do_rootfs: Function failed: do_rootfs

This is actually a runtime dependency. Thus, it suffices to make this recipe
provide libnvdimm.

Cc: Megha Dey <megha.dey@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>