grub-efi: fix luv-netboot build issue
While building the luv-netboot-image, the following error was observed:

ERROR: grub-efi-2.02-r0 do_mkimage: Function failed: do_mkimage (log
file is located at
/home/megha/luv-yocto/build/tmp/work/core2-64-oe-linux/grub-efi/2.02-r0/temp/log.do_mkimage.22866)
ERROR: Logfile of failure stored in:
/home/megha/luv-yocto/build/tmp/work/core2-64-oe-linux/grub-efi/2.02-r0/temp/log.do_mkimage.22866
Log data follows:
| DEBUG: SITE files ['endian-little', 'common-linux', 'common-glibc',
'bit-64', 'x86_64-linux', 'common']
| DEBUG: Executing shell function do_mkimage
| grub-mkimage: error: cannot open
`/home/megha/luv-yocto/build/tmp/deploy/images/qemux86-64/luv-netboot-image-qemux86-64.hddimg':
No such file or directory.
| WARNING: exit code 1 from a shell command.

Ideally, we would want luv-netboot-image:do_mkimage (which generates the
XXX.hddimg) to run before grub-efi:do_mkimage (which generated the final
efi image). Currently, grub_efi:do_deploy depends on
luv-netboot-image:do_mkimage.

Specifying the dependence between luv-netboot-image:do_mkimage and
grub-efi:do_mkimage explicitly ensures we do not encounter this error.

Signed-off-by: Megha Dey <megha.dey@linux.intel.com>