fwts: Include the fix for tests dependency on libfdt
A recent release of FWTS has test dependency on libfdt causing the build
failures in luv. A fix has been included in FWTS soon after the release
and it makes sense to include it in luv to avoid such build errors as
follows:

cc1: all warnings being treated as errors
Makefile:3540: recipe for target 'opal/fwts-reserv_mem.o' failed
make[3]: *** [opal/fwts-reserv_mem.o] Error 1
make[3]: *** Waiting for unfinished jobs....
opal/power_mgmt_info.c: In function 'cpuidle_states_test':
opal/power_mgmt_info.c:75:5: error: 'test_len' may be used uninitialized
in this function [-Werror=maybe-uninitialized]
if (prop1_len == prop2_len)
    ^
Makefile:3526: recipe for target 'opal/fwts-power_mgmt_info.o' failed
make[3]: *** [opal/fwts-power_mgmt_info.o] Error 1
Makefile:3871: recipe for target 'all-recursive' failed
ERROR: Function failed: do_compile (log file is located at
[...]/luv/build/tmp/work/qemux86_64-oe-linux/fwts/V17.05.00+gitAUTOINC+
f4d8710dc5-r0/temp/log.do_compile.9036)

Cc: Ricardo Neri <ricardo.neri@intel.com>
Signed-off-by: Gayatri Kammela <gayatri.kammela@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>