efivarfs-test: Ensure the kernel source available
The efivarfs-test is looking for kernel-source COPYING file.
So the changes in this patch will make sure that the kernel
source code is downloaded and available before executing the
efivarfs test do_populate_lic function.
Error logs:
build$ bitbake luv-live-image
...
..........
WARNING: efivarfs-test-1.0-r0 do_populate_lic: Could not copy license file /luv-live-image/luv-yocto/build/tmp/work-shared/qemuarm64/kernel-source/COPYING to luv-live-image/luv-yocto/build/tmp/work/aarch64-oe-linux/efivarfs-test/1.0-r0/license-destdir/efivarfs-test/COPYING: [Errno 2] No such file or directory: 'luv-live-image/luv-yocto/build/tmp/work-shared/qemuarm64/kernel-source/COPYING'
ERROR: efivarfs-test-1.0-r0 do_populate_lic: QA Issue: efivarfs-test: LIC_FILES_CHKSUM points to an invalid file: luv-live-image/luv-yocto/build/tmp/work-shared/qemuarm64/kernel-source/COPYING [license-checksum]
ERROR: efivarfs-test-1.0-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: efivarfs-test-1.0-r0 do_populate_lic:
ERROR: efivarfs-test-1.0-r0 do_populate_lic: Function failed: populate_lic_qa_checksum
ERROR: Logfile of failure stored in: luv-live-image/luv-yocto/build/tmp/work/aarch64-oe-linux/efivarfs-test/1.0-r0/temp/log.do_populate_lic.12125
ERROR: Task (luv-live-image/luv-yocto/meta-luv/recipes-core/efivarfs/efivarfs-test.bb:do_populate_lic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 914 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  luv-live-image/luv-yocto/meta-luv/recipes-core/efivarfs/efivarfs-test.bb:do_populate_lic
Summary: There were 2 WARNING messages shown.
Summary: There were 4 ERROR messages shown, returning a non-zero exit code.
luv-live-image/luv-yocto/build$

Changes V0->V1:
The changes made from do_patch[depends] += "linux-luv:do_patch" to
do_populate_lic[depends] += "virtual/kernel:do_shared_workdir" as
suggested by Ricardo Neri on LUV ML.

Suggested-by: Ricardo Neri <ricardo.neri@intel.com>
Signed-off-by: Naresh Bhat <naresh.bhat@linaro.org>
Signed-off-by: Megha Dey <megha.dey@linux.intel.com>