bits: only build grub EFI image for target builds
The function do_install is called for both target and native builds. Thus, for
native builds, the aforementioned function attempts to build an image for
BITS_TARGET. This is incorrect and unnecessary for native builds and causes
the following error:

    NOTE: make -j8 -e MAKEFLAGS= mkimage-grub-i386-efi
    bits-grub-mkimage: error: cannot open `[work_dir]/[native_dir]/bits-native/
                       [bit_version]/git/build/grub-inst/lib/grub/i386-efi/
                       moddep.lst': No such file or directory.
    make: *** [mkimage-grub-i386-efi] Error 1
    ERROR: oe_runmake failed

The only purpose of the native build is to install the grub-mkimage utility to
be used to build a grub EFI image for target builds. Is not necessary to build a
grub EFI image for native builds nor any of the other BITS components. Hence,
do_install can safely become do_install_class-target.

Reported-by: Megha Dey <megha.dey@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>