util-linux: fix build errors after updating to 2.32
On the sumo branch of poky, util-linux version has been updated to
2.32 from 2.31.

After updating to 2.32, we see the following error on some systems:
sys-utils/lsns.c: In function ‘get_netnsid_via_netlink_send_request’:
sys-utils/lsns.c:332:20: error: ‘RTM_GETNSID’ undeclared (first use
in this function)
nlh->nlmsg_type = RTM_GETNSID;
                  ^
sys-utils/lsns.c:332:20: note: each undeclared
identifier is reported only once for each function it appears in
sys-utils/lsns.c: In function ‘get_netnsid_via_netlink_recv_response’:
sys-utils/lsns.c:362:30: error: ‘RTM_NEWNSID’ undeclared (first use
in this function)
&& nlh->nlmsg_type == RTM_NEWNSID))
                      ^

This error is seen on system, where the minimum version of kernel
headers installed is < v4.2, the first version where RTM_GETNSID and
RTM_NEWNSID were defined.

A cleaner solution is to add the minimum version dependency in the
configure file, but for now we avoid this error, by simply not
compiling the lsns module, as we do not require it in LUV.

Signed-off-by: Megha Dey <megha.dey@linux.intel.com>