grub-efi: chainloader: fix indentation issue
When gcc is exectuted with -Werror=misleading-indentation (as does
bitbake), the following warning (and, therefore, an error) is
observed:

../../grub-2.00/grub-core/loader/efi/chainloader.c:
 In function 'grub_shim_load_image':
../../grub-2.00/grub-core/loader/efi/chainloader.c:497:7:
 error: this 'if' clause does not guard... [-Werror=misleading-indentation]
       if (section->characteristics & 0x02000000)
       ^~
../../grub-2.00/grub-core/loader/efi/chainloader.c:501:2: note:
 ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
  sect_size = section->virtual_size;
  ^~~~~~~~~

This only fixes the indentation. No functional changes are made.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>