chipsec: set COMPATIBLE_HOST variable
At the moment, chipsec can only be built for x86-64 and i386 hosts. Thus,
set COMPATIBLE_HOST accordingly. Otherwise, bitbake will attempt to
parse the recipe for unsupported hosts and, if building for aarch64, the
following errors or warnings will be observed:

When building from jethro:

    NOTE: Error during finalise of [...]/meta-luv/recipes-core/chipsec/
          chipsec_git.bb
    ERROR: ExpansionError during parsing [...]/meta-luv/recipes-core/
           chipsec/chipsec_git.bb: Failure expanding variable
           oe_runmake_call: SkipPackage: TARGET_ARCH aarch64 not supported!

When building from master:

    WARNING: Exception during build_dependencies for oe_runmake_call
    WARNING: Error during finalise of [...]/meta-luv/recipes-core/chipsec/
	         chipsec_git.bb

Cc: Megha Dey <megha.dey@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>