chipsec: Ship 64-bit binary files only in 64-bit packages
The files TianoCompress.bin and LzmaCompress.bin are distributed
in binary form. It's format is ELF64. Thus, only ship them for 64-bit
builds. They could not be used in 32-bit builds anyway. We also avoid this
package quality error:

ERROR: chipsec-1.2.5+-r0 do_package_qa: QA Issue: Architecture did not match
(x86-64, expected x86) on /work/qemux86-oe-linux/chipsec/1.2.5+-r0/packages-
split/chipsec/usr/lib/python2.7/site-packages/chipsec/chipsec_tools/linux/
TianoCompress.bin
Architecture did not match (x86-64, expected x86) on /work/qemux86-oe-linux/
chipsec/1.2.5+-r0/packages-split/chipsec/usr/lib/python2.7/site-packages/
chipsec/chipsec_tools/linux/LzmaCompress.bin [arch]
ERROR: chipsec-1.2.5+-r0 do_package_qa: QA Issue: Architecture did not match
(x86-64, expected x86) on /work/qemux86-oe-linux/chipsec/1.2.5+-r0/packages-
split/chipsec-dbg/usr/lib/python2.7/site-packages/chipsec/chipsec_tools/
linux/.debug/TianoCompress.bin
Architecture did not match (x86-64, expected x86) on /work/qemux86-oe-linux
/chipsec/1.2.5+-r0/packages-split/chipsec-dbg/usr/lib/python2.7/site-
packages/chipsec/chipsec_tools/linux/.debug/LzmaCompress.bin [arch]
ERROR: chipsec-1.2.5+-r0 do_package_qa: QA run found fatal errors.
Please consider fixing them.
ERROR: chipsec-1.2.5+-r0 do_package_qa: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /data/code/luv-yocto-32/build/tmp/
work/qemux86-oe-linux/chipsec/1.2.5+-r0/temp/log.do_package_qa.108703
ERROR: Task (/data/code/luv-yocto-32/meta-luv/recipes-core/chipsec/
chipsec_git.bb:do_package_qa) failed with exit code '1'

Cc: Megha Dey <megha.dey@intel.com>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>