ovmf: update to a newer version
Bump OVMF to a newer version. This update requires the following changes:

*Now OVMF supports GCC5, update our toolchain fixup accordingly.
*The BaseTools build flags needs to be updated to use include and library
 directories from bitbake's native sysroot.
*Update one of our patches to the new codebase.
*For now, we disable parallel builds. This is because there is a race
 condition that I did not have time to debug. It manifest itself as:

======================================================================
ERROR: testRandomDataCycles (TianoCompress.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/code/edk2/BaseTools/Tests/TianoCompress.py", line 65, in testRandomDataCycles
    self.compressionTestCycle(data)
  File "/data/code/edk2/BaseTools/Tests/TianoCompress.py", line 52, in compressionTestCycle
    finish = self.ReadTmpFile('output2')
  File "/data/code/edk2/BaseTools/Tests/TestTools.py", line 143, in ReadTmpFile
    f = open(self.GetTmpFilePath(fileName), 'r')
IOError: [Errno 2] No such file or directory: '/data/code/edk2/BaseTools/Tests/TestTempDir/output2'

----------------------------------------------------------------------

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>