core-image-efi-initramfs: add python modules needed by chipsec
For parsing the XML configuration files, chipsec needs the python-codecs module.
Otherwise, this error is observed:

    [*] looking for platform config in '/usr/lib/python2.7/site-packages/chipsec
        /cfg/common.xml'..
    [-] Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/chipsec/chipset.py", line 418, in
        init_cfg self.init_xml_configuration()
      File "/usr/lib/python2.7/site-packages/chipsec/chipset.py", line 323, in
        init_xml_configuration self.init_cfg_xml
        ( os.path.join(_cfg_path,'common.xml'), self.code )
      File "/usr/lib/python2.7/site-packages/chipsec/chipset.py", line 339, in
        init_cfg_xml tree = ET.parse( fxml )
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
        tree.parse(source, parser)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
        parser.feed(data)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
        self._parser.Parse(data, 0)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1538, in
        _start_list tag = fixname(tag)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _fixname
        self._names[key] = name = self._fixtext(name)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1511, in _fixtext
        return text.encode("ascii")
    LookupError: no codec search functions registered: can't find encoding

The subprocess modules is neede by the chipsec SMMR module. If missing, this
error is observed:

    [*] Verifying that SMRR range base & mask are the same on all logical CPUs..
    [-] Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/chipsec_main.py", line 291, in
        run_module result = modx.run( module_argv )
      File "/usr/lib/python2.7/site-packages/chipsec/module.py", line 80, in run
        result = self.mod_obj.run(module_argv)
      File "/usr/lib/python2.7/site-packages/chipsec/modules/common/smrr.py",
        line 165, in run return self.check_SMRR( do_modify )
      File "/usr/lib/python2.7/site-packages/chipsec/modules/common/smrr.py",
        line 115, in check_SMRR for tid in
        range(self.cs.msr.get_cpu_thread_count()):
      File "/usr/lib/python2.7/site-packages/chipsec/hal/msr.py", line 70, in
        get_cpu_thread_count thread_count = self.helper.get_threads_count()
      File "/usr/lib/python2.7/site-packages/chipsec/helper/oshelper.py",
        line 327, in get_threads_count return self.helper.get_threads_count()
      File "/usr/lib/python2.7/site-packages/chipsec/helper/linux/helper.py",
        line 761, in get_threads_count import subprocess
    ImportError: No module named subprocess

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>