image-live.bbclass: optionally use xorriso to build ISO images
Commits 5e360ca13572 ("image-live.bbclass: fix iso + efi only") and
b75505ec33aa ("image-live.bbclass: DEPENDS on syslinux") make image-live
depend on syslinux even for non PCBIOS live images. This is because
mkisofs require syslinux/isolinux.bin, which is provided by syslinux. This
is not a problems for architectures that syslinux support. However, if we
intend to build a live image for unsupported archs (e.g., aarch64) this
becomes a problem. We will see the following error:

ERROR: Nothing PROVIDES 'syslinux'
ERROR: syslinux was skipped: incompatible with host aarch64-oe-linux (not
       in COMPATIBLE_HOST)
ERROR: Required build target '[live image recipe here]' has no buildable
        providers.

xorriso does not require a syslinux binary nor isohybrid. Thus, we can use
it as alternative to mkisofs.

An EFI_USEXORRISO variable is added that needs to be defined by recipe
that inherit from image-live.bbclass. The variable is prepended with EFI_
to make clear the fact that xorriso will only be used for images that
can boot via UEFI. If EFI is not used, mkisofs, along with syslinux
will continue to be used.

Cc: Robert Yang <liezhi.yang@windriver.com>
Cc: Naresh Bhat <naresh.bhat@linaro.org>
Originally-by: Naresh Bhat <naresh.bhat@linaro.org>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>