linux-yocto-efi-test: use separate defconfigs for x86 and x86-64
We were using the same defconfig for both x86 (i.e., i386, 32-bit) and
x86-64. While we are lucky that this builds, sometime things do break (see
below). Thus, two separate defconfigs are now provided under the qemux86
and qemux86-64. These config files are derived from the i386_defconfig
and x86_64_defconfig from Linux v4.7, respectively. Since we already
had a x86-64 defconfig from v4.7, it was simply relocated to its new
location.

This is the error that is seen when trying to build an x86 kernel with
a x86-64 defconfig:

 [...]/tmp/work-shared/qemux86/kernel-source/scripts/mod/empty.c:1:0: error:
 code model 'kernel' not supported in the 32 bit mode
 /* empty file to figure out endianness / word size */

 [...]/tmp/work-shared/qemux86/kernel-source/scripts/mod/empty.c:1:0:
 sorry, unimplemented: 64-bit mode not compiled in
 [...]/tmp/work-shared/qemux86/kernel-source/scripts/mod/
 devicetable-offsets.c:1:0: error: code model 'kernel' not
 supported in the 32 bit mode
  #include <linux/kbuild.h>

 [...]/tmp/work-shared/qemux86/kernel-source/scripts/mod/
 devicetable-offsets.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
   HOSTCC  scripts/selinux/mdp/mdp
 [...]/tmp/work-shared/qemux86/kernel-source/scripts/Makefile.build:153:
 recipe for target 'scripts/mod/devicetable-offsets.s' failed
 make[4]: *** [scripts/mod/devicetable-offsets.s] Error 1
 make[4]: *** Waiting for unfinished jobs....
 [...]/tmp/work-shared/qemux86/kernel-source/scripts/Makefile.build:289:
 recipe for target 'scripts/mod/empty.o' failed
 make[4]: *** [scripts/mod/empty.o] Error 1
   HOSTCC  scripts/selinux/genheaders/genheaders
 [...]/tmp/work-shared/qemux86/kernel-source/scripts/Makefile.build:440:
 recipe for target 'scripts/mod' failed
 make[3]: *** [scripts/mod] Error 2
 make[3]: *** Waiting for unfinished jobs....
 [...]/tmp/work-shared/qemux86/kernel-source/Makefile:558: recipe for
 target 'scripts' failed

Cc: Megha Dey <megha.dey@intel.com>
Cc: Naresh Bhat <naresh.bhat@linaro.org>
Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>