bits: grub: core: lib: crypto: complete handling fgets return  values
Handle return values of fgets when reading the password string. While we can
obtain the length of the captured string by using strlen (buf), we still get
build warnings if the return values of fgets are not handled. Also, it is more
clear to handle the fgets value separately. This is the warning issued by the
compiler:

    build/grub/grub-core/lib/crypto.c: In function 'grub_password_get':
    build/grub/grub-core/lib/crypto.c:431:9: error: ignoring return value of 'fgets',
       declared with attribute warn_unused_result [-Werror=unused-result]
           fgets (buf, buf_size, stdin);
                 ^

fgets returns the number of characters read, or NULL when an error occurred or
no characters were read. Thus, we can return 0 in such a case. Furthermore,
the callers of this function check on zero values for errors.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>