bits: include sysmacros.h to fix build error
This patch is in preparation to updating LUV to use poky/pyro.

When building bits, we will get the following error:

.../bits/2079+gitAUTOINC+19da7046a7-r0/git/build/grub/util/getroot.c:1624:13:
error: In the GNU C Library, "major" is defined by <sys/sysmacros.h>.
.../bits/2079+gitAUTOINC+19da7046a7-r0/git/build/grub/util/raid.c:85:13:
error: In the GNU C Library, "makedev" is defined by <sys/sysmacros.h>.
For historical compatibility, it is currently defined by <sys/types.h>
as well, but we plan to remove this soon. To use "major", include
<sys/sysmacros.h> directly. If you did not intend to use a system-defined
macro "major", you should undefine it after including <sys/types.h>.

This patch includes the sysmacros.h header file in the required files.

Reviewed-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>
Signed-off-by: Megha Dey <megha.dey@linux.intel.com>