bits: rc: python: use fwrap to build python
If this flag is not used, the following compiler warning is observed:

    grub/grub-core/contrib-deps/python/Modules/arraymodule.c:1794:19:
    error: assuming signed overflow does not occur when assuming that
    (X + c) < X is always false [-Werror=strict-overflow]
          if ((step > 0 && stop < start) ||
                        ^

Furthermore, stand-alone builds of Python are built using the -fwrap cflag to
instruct the compiler to not optimize comparions between signed
variables that can wrap. Thus, we simply add the flag.

Also, by analizing the function in question (array_ass_subscr), one can
observe there exists at least one code path that leads to the (X + c) < X
comparison. This could occur if the value argument is NULL. In such a case,
step = 1, start = i, stop = + 1; which leads to:

    step > 0 && stop  < start
    1    > 0 && i + 1 < i

The second portion of the comparison is always false, provided that
i does not wrap around.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>