linux-luv: Fix build issue after updating to v4.17
Linux 4.17 starts using asm-goto to guarantee the absence of dynamic
branches x86 systems (e501ce9 "x86: Force asm-goto")

A primary prerequisite for this is of course that the compiler supports
asm-goto.(gcc > 4.5)

However, while building LUV, the following error is seen:
ERROR: linux-luv-4.17+gitAUTOINC+29dcea8877-r5 do_configure: Function
failed: do_configure (log file is located at
/home/megha/luv/build/tmp/work/qNC+29dcea8877-r5/temp/log.do_configure.1589)
| make: Entering directory
`/home/megha/luv/build/tmp/work-shared/qemux86-64/kernel-source'
| make[1]: Entering directory
`/home/megha/luv/build/tmp/work/qemux86_64-oe-linux/linux-luv/4.17+gitAUTOINC+29dcea8877-r5/linux-qemux86_64-standard
| arch/x86/Makefile:184: *** Compiler lacks asm-goto support..  Stop.
| make[1]: Leaving directory
`/home/megha/luv/build/tmp/work/qemux86_64-oe-linux/linux-luv/4.17+gitAUTOINC+29dcea8877-r5/linux-qemux86_64-standard-
| make: *** [sub-make] Error 2
| make: Leaving directory
`/home/megha/luv/build/tmp/work-shared/qemux86-64/kernel-source'
| WARNING: exit code 2 from a shell command.
| ERROR: Function failed: do_configure (log file is located at
/home/megha/luv/build/tmp/work/qemux86_64-oe-linux/linux-luv/4.17+gitAUTOINC+29dcea8
ERROR: Task
(/home/megha/luv/meta-luv/recipes-kernel/linux/linux-luv_4.17.bb:do_configure)

This happens because at the time that compiler support is checked
for (much before do_configure), bitbake has not yet built its gcc.

Thus, we make sure that we remove the .cache.mk file before the
do_configure to ensure that the check for compiler support happens again,
and this time gcc is present.

Signed-off-by: Megha Dey <megha.dey@linux.intel.com>