luv: Add systemd to PACKAGECONFIG variable for ndctl
Commit cd7101c("ndctl: fix compile issue") makes reference to the
PACKAGECONFIG variable for ndctl. Since the default value of the
PACKAGECONFIG variable is undefined for the ndctl recipe, we see
the following error:

ERROR: ndctl-v62+gitAUTOINC+11f560f404-r0 do_package:
SYSTEMD_SERVICE_ndctl value ndctl-monitor.service does not exist
ERROR: ndctl-v62+gitAUTOINC+11f560f404-r0 do_package: Function failed:
systemd_populate_packages

Thus, we need to add systemd to the PACKAGECONFIG variable for ndctl.

Signed-off-by: Megha Dey <megha.dey@linux.intel.com>