bits: grub: core: net: bootp: conserve variable qualifier
The function set_env_limn_ro receives *vend as pointer to a constant. However
the automatic variables *ptr and *ptr0 drop such qualifier, causing this
warning:

    build/grub/grub-core/net/bootp.c: In function 'grub_net_configure_by_dhcp_ack':
    build/grub/grub-core/net/bootp.c:255:30: error: passing argument 2 of
      'parse_dhcp_vendor' discards 'const' qualifier from pointer target type
       [-Werror=discarded-array-qualifiers]
          parse_dhcp_vendor (name, &bp->vendor, size - OFFSET_OF (vendor, bp), &mask);
                                  ^
    build/grub/grub-core/net/bootp.c:55:1: note: expected 'void *' but argument is
      of type 'const grub_uint8_t (*)[] {aka const unsigned char (*)[]}'
           parse_dhcp_vendor (const char *name, void *vend, int limit, int *mask)
           ^

These variables do not change the contents of *vend. Thus, we simply add
the const qualifier.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>