nvdimm-test: Ensure nvdimm builds with kernel v4.15
After updating to kernel v4.15, we faced the following error:

ERROR: nvdimm-test-1.0-r0 do_compile: oe_runmake failed
ERROR: nvdimm-test-1.0-r0 do_compile: Function failed: do_compile (log
| make -C $KERNEL/tools/testing/nvdimm M=$KERNEL/tools/testing/nvdimm/
| make[1]: Entering directory
'/home/megha/luv-yocto/build/tmp/work-shared/qemux86-64/kernel-source/tools/testing/nvdimm'
| make -C ../../../ M=$PWD
| make[2]: Entering directory
'/home/megha/luv-yocto/build/tmp/work-shared/qemux86-64/kernel-source'
| make[3]: Entering directory
'/home/megha/luv-yocto/build/tmp/work-shared/qemux86-64/kernel-build-artifacts'
| make[4]: *** No rule to make target
'/home/megha/luv-yocto/build/tmp/work-shared/qemux86-64/kernel-
source/tools/testing/nvdimm/../../../drivers/nvdimm/core.o',
needed by
'/home/megha/luv-yocto/build/tmp/work-shared/qemux86-64/kernel-
source/tools/testing/nvdimm/libnvdimm.o'.
Stop.

After doing a git bisect, the faulty commit was found to be:
1e4078f0bba(x86/unwinder: Make CONFIG_UNWINDER_ORC=y the default in the
64-bit defconfig)

Not sure why this change triggers this build error. But since we do not
need the CONFIG_UNWINDER_ORC to be enabled in LUV, disable it. Disabling
it means making FRAME_POINTER as unwinder instead of ORC. If we disable
ORC using CONFIG_UNWINDER_ORC=n in quirks_cfg file, it is being
over-written by x86_64 defconfig, so, we should make FRAME_POINTER as
preferred unwinder instead of ORC.

Cc: Naresh Bhat <naresh.bhat@linaro.org>
Cc: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>
Signed-off-by: Sai Praneeth Prakhya <sai.praneeth.prakhya@intel.com>
Signed-off-by: Megha Dey <megha.dey@linux.intel.com>